### ISSUE TITLE
Make 'SDK' highlight flexible

### ISSUE THREAD

**Issue by ewillink** [eclipse-justj/justj.tools#9]
The JustJ indexes show some features in bold. This is not explained to the user. Debugging reveals that there is a hardwired pattern match to `".*\\.sdk([_.-]feature)?\\.feature\\.group"`. This was plausible in pre-Tycho days when SDK meant with-sources. But now that we can have with/without Developer Resources for all plugins/features, SDK is a misnomer and so the hardwired match may fail to highlight rationally-named primary features.

Suggest add a -bold-iu-pattern to parameterize the hardwired pattern.

**Comment by ewillink** [comment]
Thanks. Adopted by OCL without signifcant issue. [https://download.eclipse.org/modeling/mdt/ocl/builds](https://download.eclipse.org/modeling/mdt/ocl/builds)

**Comment by merks** [comment]
Very good.

FYI,  the P2 repos link

https://archive.eclipse.org/modeling/mdt/modisco/updates/releases

is not quite right and should be 

https://archive.eclipse.org/modeling/mdt/modisco/updates/release

**Comment by ewillink** [comment]
Thanks, but much worse, it should be 'ocl' not 'modisco' - a problem with progresssing four projects at once.
